version: '3.1'
services:
  rabbitmq:
    image: 'rabbitmq:3.13.2-management-alpine'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'ninja'
      RABBITMQ_DEFAULT_PASS: '1234qwer'
      RABBITMQ_ERLANG_COOKIE: 'cookie_for_clustering'
    ports:
      - '5672:5672'
      - '5671:5671'
      - '15672:15672'
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
      - './rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro'
      - './tls-gen/basic/result:/certs'
      - './rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json:ro' 
    network_mode: host
  
  nats:
    image: nats:2.10.14-alpine3.19
    command: -m 8222 -js 
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - './nats-data:/data'
    environment:
      - NATS_STREAMING_STORE_DIR=/data
    network_mode: host

