version: '3.1'

services:
  rabbitmq:
    image: 'rabbitmq:3.13.2-management-alpine'
    restart: always
    
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: '1234qwer'

    ports:
      - '5672:5672'
      - '15672:15672'

    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
