// $ sudo docker run --name rabbitmq --rm -v "$(pwd)"/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json:ro  -v "$(pwd)"/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro -v "$(pwd)"/tls-gen/basic/result/:/certs -p 5671:5671 -p 15671:15671 rabbitmq:3.13.2-management-alpine

version: '3.1'

services:
  rabbitmq:
    image: 'rabbitmq:3.13.2-management-alpine'
    restart: always

    environment:
      RABBITMQ_DEFAULT_USER: 'ninja'
      RABBITMQ_DEFAULT_PASS: '1234qwer'
      RABBITMQ_ERLANG_COOKIE: 'cookie_for_clustering'
    ports:
      - '5672:5672'
      - '5671:5671'
      - '15672:15672'

    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
      - './rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro'
      - './tls-gen/basic/result:/certs'
      - './rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json:ro'

    network_mode: host